comment_width = 100
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
max_width = 100
merge_derives = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
